remote_theme: pages-themes/leap-day@v0.2.0
title: 我的涂鸦站
description: 我的涂鸦站
# theme: jekyll-theme-modernist
timezone: Asia/Shanghai
nav:
- name: Home
  link: /
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one  
github:
  is_project_page: false